### ISSUE TITLE
Module not found: Can't resolve 'react-transition-group' in '*\@steveeeie\react-page-transition\dist'

### ISSUE THREAD

**Issue by aleksandrakojic** [Steveeeie/react-page-transition#1]
Hey there,

You package seams very cool and easy to use! :)
I try to implement it in my project, but first error that I got, was that it's not types, that it doesn't have @types/@steveeie/react-page-transition module. I resolved it by making index.d.ts file and declaring the module inside. 
It worked well, but on the other hand, I got this error too:
`Module not found: Can't resolve 'react-transition-group' in '*\@steveeeie\react-page-transition\dist'
`

Is there any solution, please ? :)

Thanks in advance !

**Comment by Steveeeie** [comment]
Hey @aleksandraDev, `react-transition-group` is a peer dependency. Have you tried to install it separately?

**Comment by aleksandrakojic** [comment]
> Hey @aleksandraDev, `react-transition-group` is a peer dependency. Have you tried to install it separately?

Hey hey, sorry for late response, I thought that `react-transition-group` was installed with the package, so instaling it separatly, as you said, and solved my problem with that error, thank you ! :)

But the animation didn't happend. I figure out that BrowserRouter is blocking the animations (the same thing happend when I tested `react-spring`), so I removed it and page transition animation worked like a charm. I don't know why it behaves like that , the routes change in URL, but I stay on the same page. :/ (maybe it's a new version of BrowserRouter, I haven't tested with the oldest one)

Anyway, thanks for your feedback ! One again, it's a cool package, great job! ;)
You may close this issue ! :)

Best regards,
Aleksandra

**Comment by Steveeeie** [comment]
Hey Aleksandra,

Interesting, I'm going to work on a version 2 of this package after Christmas using `react-spring` and will keep an eye on `BrowserRouter` to see how it effects things. Thanks for your feedback 👍 

Regards,

Steve

**Comment by genesiscz** [comment]
Actualy had the same problem, got it working, then the compiler was screaming I don't have default export of PageTransition in the dist file. adding that manually didnt help, it was doing something but the animation was not doing anything. I downloaded the git folder, included into my src, imported and it worked all okay. Not sure why, have any ideas?

**Comment by Steveeeie** [comment]
Hey @genesiscz, 

Sorry for the late reply, I have only just seen your response.

Could you confirm what version you currently have installed?

**Comment by genesiscz** [comment]
1.1.1

**Comment by mbouadeus** [comment]
I'm having the same error on this thread but installing react-transition-group does not fix it.

`Error in ./~/@steveeeie/react-page-transition/dist/index.cjs.js
Module parse failed: /*/node_modules/@steveeeie/react-page-transition/dist/index.cjs.js Unexpected token (261:98)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (261:98)
 @ ./src/App.js 16:27-70`

**Comment by genesiscz** [comment]
Can you confirm it works if you download the repo directly into src and include the files from there?

**Comment by mbouadeus** [comment]
The error changes to Module not found.
Module not found: 'src/lib/react-page-transition/PageTransition' in /*/project-name/src

I looked over the module and can’t figure out why it can’t find it. I’m thinking it’s a web pack issue.

**Comment by mbouadeus** [comment]
I got it to work by using the fixed path and all the errors seem to be gone. The page was blank so I tried removing Browser Router like aleksandraDev did but I'm getting errors now because I'm using react-router without a router. I'll keep on trying to see if I can get it to work.

**Comment by RSNFreud** [comment]
I have the same issue but using installing the react-transition-group doesnt do anything. Does it need to be installed to a specific place?
