### ISSUE TITLE
slider enterAnimation: "moveFromLeft",     exitAnimation: "moveToRight", not working in MacOs safari latest version

### ISSUE THREAD

**Issue by thakuranujsingh** [Steveeeie/react-page-transition#10]

**Comment by Steveeeie** [comment]
Hi @thakuranujsingh, Looks like none of the 'moveFrom...` animations are working in latest Safari. Thanks for the heads up 👍

**Comment by Steveeeie** [comment]
Fixed as part of: https://github.com/Steveeeie/react-page-transition/releases/tag/1.2.1
