### ISSUE TITLE
When adding 100% to the height, transitions work, but scrolling no longer does

### ISSUE THREAD

**Issue by haveamission** [Steveeeie/react-page-transition#16]
So I've added the following to my style sheet:

```
html,
body,
#root {
  height: 100%;
}
```
The page shows up, the transitions work as expected, however I cannot scroll down on the page at all. Nothing "below the fold" shows at all.

How do I get around this?

**Comment by haveamission** [comment]
I had to add:

```
  z-index: 1;
  height: 100%;
  display: flex;
  flex-direction: column;
  height: 100%;
  overflow-x: hidden;
  overflow-y: auto;
  width: 100%;
```

to my wrapper

**Comment by SLDem** [comment]
@haveamission is this the wrapper for your entire app or do you add this to each main component?

**Comment by SLDem** [comment]
You have to add it to each one of your Router components.
