### ISSUE TITLE
Speed of the transitions

### ISSUE THREAD

**Issue by coenfuze** [Steveeeie/react-page-transition#17]
Great package! Is possible to override the transition speed? Thanks in advance.

**Comment by Steveeeie** [comment]
Thanks @l9mon8,

Sorry but the durations are fixed right now and I don't have the time to implement a change for this.

**Comment by coenfuze** [comment]
No problem, figured it out, I'll create a pull request for you if I have some spare time ;-)

**Comment by Steveeeie** [comment]
Cool, feel free to open a PR 👍
