### ISSUE TITLE
Support for React 17

### ISSUE THREAD

**Issue by clicktodev** [Steveeeie/react-page-transition#18]
React 17 causes this warning:

> findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference

Disabling strict mode doesn't fix the issue.

**Comment by Steveeeie** [comment]
Thanks for raising this, I will resolve as soon as possible.

**Comment by clicktodev** [comment]
This might help with fixing the issue:
https://github.com/reactjs/react-transition-group/issues/668

**Comment by Steveeeie** [comment]
@hichemfantar I'm struggling to reproduce the error. 

I have successfully updated the advanced demo to use StrictMode and version 17 of React: https://codesandbox.io/s/advanced-react-page-transition-demo-z8hmd.

I have also successfully updated the basic demo to use StrictMode and version 17 of React: 
https://codesandbox.io/s/basic-react-page-transition-demo-rk0uv

**Comment by clicktodev** [comment]
Weird, It's working now. Maybe it's because I'm using node 12 now instead of 14 like I was before.
I'll test it again with node 14 and get back to you asap.

**Comment by hichemfantar** [comment]
Ok it seems like It's working on both now. Have no idea what I messed up previously.
Anyway, Now the error remains in strict mode however the app continuers to function normally despite the error, also disabling strict mode makes the error go away.

**Comment by clicktodev** [comment]
Ok it seems like It's working on both now. Have no idea what I messed up previously.
Anyway, Now the warning appears in the console in strict mode however the app continuers to function normally despite the warning, also disabling strict mode makes the warning go away.

**Comment by Steveeeie** [comment]
Thank you for looking into this for me. 

I'm seeing the console warning too, i will try to resolve it this week.

**Comment by clicktodev** [comment]
Cool man, looking forward to the fix!

**Comment by antonnystedt** [comment]
I still get this error.

**Comment by clicktodev** [comment]
Apparently this is an issue with [react-transition-group](https://github.com/reactjs/react-transition-group/issues/687)
@Steveeeie can't fix it unless a fork is made of react-transition-group with the new API or this package gets rewritten on top of a different animation library.

**Comment by clicktodev** [comment]
Apparently there's no official fix for this and all the workarounds have certain pitfalls.
I believe it would be better to port the library to Framer Motion.
These are some nice resources:
https://stackoverflow.com/questions/70239122/react-router-dom-v6-with-framer-motion-v4
https://www.geeksforgeeks.org/page-transition-in-react-js-using-framer-motion/
https://www.framer.com/docs/guide-upgrade/#50

**Comment by Steveeeie** [comment]
That's not a bad shout. I have a lot of experience with Framer Motion. Switching to it would remove a lot of the configuration and make the whole thing a lot more plug and play.

**Comment by clicktodev** [comment]
Looking forward to the switch to framer motion, I believe you'll bump this library to the next major version since it would probably be incompatible with the previous release.
I don't have a lot of experience with framer motion but I'll be glad to help in anyway i can.

**Comment by Steveeeie** [comment]
See: https://github.com/Steveeeie/react-page-transition/issues/33
