### ISSUE TITLE
Does this doesn't work with latest version of react or react-router-dom ?

### ISSUE THREAD

**Issue by primeTanM** [Steveeeie/react-page-transition#31]
Does this doesn't work with latest version of react or react-router-dom after doing this:
```
const AnimatedRoutes = () => {
  const location = useLocation();
  return (
    <PageTransition
      preset="moveToLeftFromRight"
      transitionKey={location.pathname}
    >
      <Routes location={location} key={location.pathname}>
        <Route exact path="/" element={<Home />} />
        <Route exact path="/about" element={<About />} />
        <Route exact path="/projects" element={<Projects />} />
        <Route exact path="/blogs" element={<Blog />} />
        <Route exact path="/contact" element={<Connect />} />
      </Routes>
    </PageTransition>
  );
};
```
it doesn't render anything?

**Comment by nkomp18** [comment]
It seems to be broken for latest version of react.
Error is:
` A <Route> is only ever to be used as the child of <Routes> element, never rendered directly. Please wrap your <Route> in a <Routes>.`

**Comment by stetttho** [comment]
bump - anyone got this working? also tried framer-motion, but basic slideIn (see https://codesandbox.io/s/advanced-react-page-transition-demo-z8hmd , preset “moveToLeftFromRight”) doesn’t seem to be possible with it?

**Comment by LibanWasTaken** [comment]
bump#2 still don't know how to use it with routes and stuff, although wrapping the Route with Routes seems to resolve the error, but nothing except the navbar renders

**Comment by c0ncentus** [comment]
nowadays "exact" is deprecated and "render" seems also depracated ...
need some works around to put version up to date ...

**Comment by Steveeeie** [comment]
See: https://github.com/Steveeeie/react-page-transition/issues/33
