### ISSUE TITLE
Add Type Declarations

### ISSUE THREAD

**Issue by Steveeeie** [Steveeeie/react-page-transition#4]

**Comment by ljhskyso** [comment]
any chance this package can support typescript?

**Comment by Steveeeie** [comment]
@ljhskyso I have planned to add support for a while. I currently don't have time to implement this.

**Comment by ljhskyso** [comment]
> @ljhskyso I have planned to add support for a while. I currently don't have time to implement this.

@Steveeeie - sounds good. look forward to it. Also, I'll see if I got time to help on this. Any document for me to start with?

**Comment by Steveeeie** [comment]
Not looking to add this any time soon

**Comment by Steveeeie** [comment]
Added via release 1.3.0
